USE customer_behavior;
SELECT * FROM customer;

-- Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_amount) AS total_revenue_generated
FROM customer
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?

SELECT customer_id,discount_applied, purchase_amount
FROM customer
WHERE discount_applied = "Yes"
	 AND purchase_amount > ( SELECT AVG(purchase_amount) FROM customer)
ORDER BY purchase_amount DESC;  
-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating),2) AS average_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY average_review_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

SELECT shipping_type, ROUND(AVG(purchase_amount),2) AS Average_Purchase_Amounts
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT  subscription_status,COUNT(customer_id) AS Total_Customer,
ROUND(AVG(purchase_amount),2) AS Average_Spend, 
SUM(purchase_amount) AS Total_Revenue
FROM customer
GROUP BY subscription_status
ORDER BY Total_Revenue DESC;

-- Q6 Which 5 products have the highest percentage of purchases with discounts applied? 

SELECT item_purchased,
 ROUND(
 COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END)*100.0/COUNT(*),2
 ) AS Percentage_of_purchases
FROM customer
GROUP BY item_purchased
ORDER BY Percentage_of_purchases DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment.

SELECT customer_segments, 
        COUNT(*) AS total_customers
FROM (
         SELECT customer_id,
   CASE 
	   WHEN previous_purchases = 1 THEN 'New'
       WHEN previous_purchases  BETWEEN 2 AND 10 THEN 'Returning'
	   ELSE 'Loyal'
END AS customer_segments 
FROM customer
) AS t
GROUP BY customer_segments;


-- Q8. What are the top 3 most purchased products within each category?

  SELECT category, product_id, total_purchases
FROM (
    SELECT 
        category,
        product_id,
        COUNT(*) AS total_purchases,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(*) DESC
        ) AS rank_in_category
    FROM orders
    GROUP BY category, product_id
) ranked
WHERE rank_in_category <= 3;  


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?

SELECT age_group, SUM(purchase_amount) AS total_revenue_generated
FROM customer
GROUP BY age_group
ORDER BY total_revenue_generated;
